docker_hosts:
  hosts:
    kube-node-1:
      ansible_host: 49.12.71.116
      ansible_user: root
      ip: 192.168.1.1
      access_ip: 192.168.1.1

kube-master:
  children:
    docker_hosts:

etcd:
  children:
    kube-master:

kube-node:
  children:
    docker_hosts:

k8s-cluster:
  children:
    kube-node:
    kube-master: